2025-09-01 21:32:35,825 INFO    MainThread:161298 [wandb_init.py:setup_run_log_directory():686] Logging user logs to /home/wildanaziz/yolo_auto_train/wandb/run-20250901_213235-erh1m7er/logs/debug.log
2025-09-01 21:32:35,825 INFO    MainThread:161298 [wandb_init.py:setup_run_log_directory():687] Logging internal logs to /home/wildanaziz/yolo_auto_train/wandb/run-20250901_213235-erh1m7er/logs/debug-internal.log
2025-09-01 21:32:35,825 INFO    MainThread:161298 [wandb_init.py:init():813] calling init triggers
2025-09-01 21:32:35,825 INFO    MainThread:161298 [wandb_init.py:init():818] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-01 21:32:35,826 INFO    MainThread:161298 [wandb_init.py:init():854] starting backend
2025-09-01 21:32:35,826 INFO    MainThread:161298 [wandb_init.py:init():857] sending inform_init request
2025-09-01 21:32:35,828 INFO    MainThread:161298 [wandb_init.py:init():865] backend started and connected
2025-09-01 21:32:35,829 INFO    MainThread:161298 [wandb_init.py:init():936] updated telemetry
2025-09-01 21:32:35,837 INFO    MainThread:161298 [wandb_init.py:init():960] communicating run to backend with 90.0 second timeout
2025-09-01 21:32:36,813 INFO    MainThread:161298 [wandb_init.py:init():1011] starting run threads in backend
2025-09-01 21:32:36,948 INFO    MainThread:161298 [wandb_run.py:_console_start():2494] atexit reg
2025-09-01 21:32:36,948 INFO    MainThread:161298 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-09-01 21:32:36,948 INFO    MainThread:161298 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-09-01 21:32:36,948 INFO    MainThread:161298 [wandb_run.py:_redirect():2434] Redirects installed.
2025-09-01 21:32:36,949 INFO    MainThread:161298 [wandb_init.py:init():1057] run started, returning control to user process
2025-09-01 21:32:37,204 INFO    MainThread:161298 [wandb_run.py:_finish():2260] finishing run wildanaziz-braw/yolo_auto_train/erh1m7er
2025-09-01 21:32:37,204 INFO    MainThread:161298 [wandb_run.py:_atexit_cleanup():2459] got exitcode: 0
2025-09-01 21:32:37,204 INFO    MainThread:161298 [wandb_run.py:_restore():2441] restore
2025-09-01 21:32:37,205 INFO    MainThread:161298 [wandb_run.py:_restore():2447] restore done
2025-09-01 21:32:38,928 INFO    MainThread:161298 [wandb_run.py:_footer_sync_info():3855] logging synced files
